version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql_med_api
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=vollmed
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - .docker/mysql-data:/var/lib/mysql

volumes:
  mysql-data:
